FE/public/index.html
FE/src/components/Navbar.jsx

메인페이지에서 Back버튼은 필요가 없어 useLocation을 사용하여 조건부 설정으로 안 보이도록 설정하였습니다.

#16 fix: Navbar Back버튼 조건부 설정

---

FE/README.md
FE/src/components/Navbar.jsx

fix: Navbar Back버튼 조건부 설정+Readme 삭제

#16 fix: Navbar Back버튼 조건부 설정+Readme 삭제

---

FE/src/App.jsx
FE/src/components/Header.jsx
FE/src/pages/MainPage.jsx

#19 fix: Header props 설정으로 유연하게 재사용 가능하도록 구현

#19 fix: Header props 설정으로 유연하게 재사용 가능하도록 구현

---

FE/src/pages/MainPage.jsx

메인페이지 구조 세팅 수정 

---

FE/src/App.jsx
FE/src/pages/MainPage.jsx
FE/src/pages/NoticePage.jsx

#35 feat:community 섹션 추가

---

FE/package-lock.json
FE/package.json
FE/src/main.jsx

#39 main branch 최신화

---

FE/src/App.jsx
FE/src/pages/JoinPage.jsx

#51 feat: 회원가입 페이지(JoinPage) 구성

---

FE/src/pages/MainPage.jsx
FE/src/pages/NoticePage.jsx
FE/src/pages/WeatherPage.jsx

#53 Style : MainPage, NoticePage, WeatherPage css 테두리 설정

---

FE/.github/workflows/deploy.yml

#45 github actions CI/CD 구축수정

---

README.md

Main branch 최신화

---

package-lock.json
package.json
src/components/Footer.jsx
src/components/Header.jsx
src/components/Navbar.jsx

#53 Footer,Navbar,Header CSS 수정 및 병합 충돌 해결

#53 Footer,Navbar,Header CSS 수정 및 병합 충돌 해결

---

src/App.jsx
src/pages/LoginPage.jsx

기존 만들어 뒀던 로그인 페이지 파일에 페이지 코드 작성

#65 feat: 로그인 페이지(LoginPage) 구성

---

src/App.jsx
src/pages/CustomerServicePage.jsx
src/pages/NoticePage.jsx

CustomerServicePage 추가

---

src/components/Button/Button.jsx
src/pages/MainPage.jsx

#53 fix: Dom버그 수정 및 MainPageWrapper CSS수정

#53 fix: Dom버그 수정 및 MainPageWrapper CSS수정

---

src/App.jsx
src/pages/MatePage.jsx

#70 doc : MatePage 생성

---

src/App.jsx
src/pages/CustomerServicePage.jsx
src/pages/MyPage.jsx

#72 feat: 마이페이지(MyPage) 생성

---

src/App.jsx
src/pages/CustomerServicePage.jsx
src/pages/MainPage.jsx
src/pages/MatePage.jsx
src/pages/MessagePage.jsx
src/pages/NoticePage.jsx
src/pages/ReceivedMessagesPage.jsx
src/pages/SentMessagesPage.jsx
src/pages/WeatherPage.jsx

#74 doc : 기존 페이지 수정 및 Message 관련 페이지 추가

---

src/pages/MyPage.jsx

마이페이지(MyPage) 디자인, 페이지 연결구조 수정

#76 feat: 마이 페이지(MyPage) 수정

---

package-lock.json
package.json
src/App.jsx
src/pages/DogCommunity.jsx
src/pages/LikeCommunity.jsx
src/pages/WorkCommunity.jsx

#78, #79, #80, #81 각 커뮤니티 페이지 및 좋아요한 게시물페이지 및 검색기능 구현완료"

#78, #79, #80, #81 각 커뮤니티 페이지 및 좋아요한 게시물페이지 및 검색기능 구현완료"

---

src/App.jsx

#85 feat: 정보수정 페이지(EditPage) props 에러 해결

---

src/App.jsx
src/components/Navbar.jsx
src/pages/DogCommunity.jsx
src/pages/MainPage.jsx
src/pages/NoticePage.jsx
src/pages/PostDetail.jsx
src/pages/PostPage.jsx
src/pages/WorkCommunity.jsx

#87 #88 feat: 게시물 상세페이지와 게시물 글쓰기 페이지 구현 + 메인페이지 기능 연결 + Navbar 가운데정렬  + 병합오류 해결

#87 #88 feat: 게시물 상세페이지와 게시물 글쓰기 페이지 구현 + 메인페이지 기능 연결 + Navbar 가운데정렬  + 병합오류 해결

---

package-lock.json
src/components/Button/Button.jsx
src/components/Footer.jsx
src/components/Header.jsx
src/components/Navbar.jsx
src/pages/CustomerServicePage.jsx
src/pages/MainPage.jsx
src/pages/MatePage.jsx
src/pages/MessagePage.jsx
src/pages/ReceivedMessagesPage.jsx
src/pages/SentMessagesPage.jsx
src/pages/WeatherPage.jsx

스타일 수정 및 코드 리펙토링

---

src/App.jsx
src/components/FilterComponent.jsx
src/components/Footer.jsx
src/components/GlobalStyle.jsx
src/components/Header.jsx
src/components/Navbar.jsx
src/pages/DogCommunity.jsx
src/pages/PostPage.jsx

#90 #92 #93  style: 반응형 셋팅 및 드래그방지 기능 및 label 클릭시 input 자동이동 셋팅

#90 #92 #93  style: 반응형 셋팅 및 드래그방지 기능 및 label 클릭시 input 자동이동 셋팅

---

src/pages/CustomerServicePage.jsx

CustomerServicePage 이메일 선택지 생성

---

src/pages/EditPage.jsx
src/pages/MyPage.jsx
src/pages/PetAddPage.jsx
src/pages/PetEditPage.jsx

반응형 화면 전환 시 보이지 않는 버튼 위치 조정 및 필요한 페이지 이동 텍스트 버튼 추가

#98 feat:마이페이지(MyPage) 텍스트 버튼추가 & 정보수정 페이지, 반려견 정보추가 페이지, 반려견 정보수정 페이지 반응형 수정

---

src/pages/MatePage.jsx

#104 feat : MatePage 검색 기능 추가 및 api 세팅

---

src/App.jsx
src/pages/MatePage.jsx
src/pages/MessagePage.jsx
src/pages/ReceivedMessagesPage.jsx
src/pages/SentMessagesPage.jsx

Conf: API 세팅

---

src/components/Pages/CommonComponents.jsx
src/components/Pages/MessagePage/MessageForm.jsx
src/components/Pages/MessagePage/MessageList.jsx
src/pages/MainPage.jsx
src/pages/MessagePage.jsx

#110 Refactor : MessagePage.jsx 컴포넌트 나누기, Fix : MainPage.jsx

---

src/components/Pages/CustomerServicePage/CustomerServiceAlert.jsx
src/components/Pages/CustomerServicePage/CustomerServiceForm.jsx
src/components/Pages/MatePage/MatePageHeader.jsx
src/components/Pages/MatePage/MateSection.jsx
src/components/Pages/MessagePage/MessageModal.jsx
src/components/Pages/MessagePage/MessageSection.jsx
src/components/Pages/MessagePage/Notification.jsx
src/components/Pages/MessagePage/SentMessageModal.jsx
src/components/Pages/MessagePage/SentMessageSection.jsx
src/components/Pages/MessagePage/Styles/MessageStyles.jsx
src/hooks/useFetch.jsx
src/pages/CustomerServicePage.jsx
src/pages/MatePage.jsx
src/pages/MessagePage.jsx
src/pages/ReceivedMessagesPage.jsx
src/pages/SentMessagesPage.jsx
src/pages/구조.txt

#119 Refactor : 컴포넌트 나누기, Conf : API 세팅

---

package-lock.json
package.json
src/api/axiosInstance.jsx
src/pages/DogCommunity.jsx
src/pages/ReceivedMessagesPage.jsx

#107 conf: API 셋팅

---

src/pages/EditPage.jsx
src/pages/JoinPage.jsx
src/pages/LoginPage.jsx
src/pages/MyPage.jsx
src/pages/PetAddPage.jsx
src/pages/PetEditPage.jsx

#127 feat: API 세팅 (LoginPage, JoinPage, MyPage, EditPage, PetAddPage, PetEditPage)

---

index.html
src/components/Pages/MessagePage/SentMessageSection.jsx
src/components/Pages/MessagePage/Styles/MessageStyles.jsx
src/pages/MatePage.jsx
src/pages/ReceivedMessagesPage.jsx
src/pages/SentMessagesPage.jsx

#129 REFAC : Message, MatePage 수정

---

src/pages/MainPage.jsx

#132 Refac : MainPage 수정

---

src/components/Pages/CustomerServicePage/CustomerServiceForm.jsx
src/hooks/useFetch.jsx
src/pages/CustomerServicePage.jsx
src/pages/MainPage.jsx
src/pages/MatePage.jsx
src/pages/ReceivedMessagesPage.jsx
src/pages/SentMessagesPage.jsx
src/pages/WeatherPage.jsx

Refac : api 연결 관련 페이지 수정
